### ISSUE TITLE
Program should not try to write to /root/chatlog

### ISSUE THREAD

**Issue by josephbisch** [egonSchiele/groupme-cli#3]
https://github.com/egonSchiele/groupme-cli/blob/f32c400e118dfa722506c7f1c1279f4c705f296f/src/Main.hs#L48

The line I link to above tries to write to `/root/chatlog`, which causes issues since I am running groupme-cli as a non-root user.

Probably should figure out the user's home directory and write to a log there, I guess?

**Comment by egonSchiele** [comment]
Ouch, it should definitely not write to root. If you send me a pr, I will merge it.
